# Generated by Django 4.2.7 on 2025-10-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_configuracionsitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_banner',
            field=models.CharField(default='#28a745', help_text='Color del banner de envío', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_cards',
            field=models.CharField(default='#ffffff', help_text='Color de fondo de las cards', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_fondo',
            field=models.CharField(default='#f8f9fa', help_text='Color de fondo del sitio', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_primario',
            field=models.CharField(default='#495057', help_text='Color principal (botones, enlaces)', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_secundario',
            field=models.CharField(default='#6c757d', help_text='Color secundario (texto, bordes)', max_length=7),
        ),
    ]
