# Generated by Django 4.2.7 on 2025-10-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_configuracionsitio_color_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='color_hover',
            field=models.CharField(default='#F4C2C2', help_text='Color de hover en navegación', max_length=7),
        ),
    ]
