# Generated by Django 4.2.7 on 2025-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_configuracionsitio_color_hover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Creados con amor', max_length=100)),
                ('icono', models.CharField(default='fas fa-heart', help_text='Clase de Font Awesome (ej: fas fa-heart, fas fa-shipping-fast)', max_length=50)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner de Fidelización',
                'verbose_name_plural': 'Banners de Fidelización',
                'ordering': ['orden'],
            },
        ),
    ]
