# Generated by Django 4.2.7 on 2025-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_bannerfidelizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerfidelizacion',
            name='color_fondo',
            field=models.CharField(default='#ffffff', help_text='Color de fondo del banner', max_length=7),
        ),
        migrations.AddField(
            model_name='bannerfidelizacion',
            name='color_icono',
            field=models.CharField(default='#495057', help_text='Color del ícono', max_length=7),
        ),
        migrations.AddField(
            model_name='bannerfidelizacion',
            name='color_texto',
            field=models.CharField(default='#6c757d', help_text='Color del texto', max_length=7),
        ),
    ]
