# Generated by Django 4.2.7 on 2025-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_bannerfidelizacion_color_fondo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Contacto', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('horarios', models.TextField(blank=True, help_text='Horarios de atención')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo', models.CharField(default='#2c3e50', help_text='Color de fondo del footer', max_length=7)),
                ('color_texto', models.CharField(default='#ecf0f1', help_text='Color del texto', max_length=7)),
                ('color_enlaces', models.CharField(default='#3498db', help_text='Color de los enlaces', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Footer',
                'verbose_name_plural': 'Configuración del Footer',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Información',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(help_text='Clase de Font Awesome (ej: fab fa-facebook)', max_length=50)),
                ('url', models.URLField()),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SobreMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre Mí', max_length=100)),
                ('contenido', models.TextField(help_text='Descripción sobre la tienda o propietario')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sobre Mí',
                'verbose_name_plural': 'Sobre Mí',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Suscríbete', max_length=100)),
                ('descripcion', models.TextField(default='Recibe nuestras ofertas y novedades')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripción',
            },
        ),
    ]
