# Generated by Django 4.2.7 on 2025-10-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_contacto_footerconfig_informacion_redsocial_sobremi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerconfig',
            name='color_redes',
            field=models.CharField(default='#e74c3c', help_text='Color de los íconos de redes sociales', max_length=7),
        ),
    ]
