# Generated by Django 4.2.7 on 2025-10-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_footerconfig_color_redes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerfidelizacion',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción breve del banner', max_length=200),
        ),
    ]
