# Generated by Django 4.2.7 on 2025-10-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_bannerfidelizacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1, help_text='Orden de aparición (1, 2, 3)')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Sección de Categoría',
                'verbose_name_plural': 'Secciones de Categorías',
                'ordering': ['orden'],
            },
        ),
    ]
